# Generated by Django 3.2.7 on 2021-09-17 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('contato', models.CharField(max_length=100, verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reduzido', models.IntegerField(verbose_name='Codigo Reduzido')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Debitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reduzido', models.IntegerField(verbose_name='Codigo Reduzido')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Historicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Lancamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('compl_historico', models.CharField(max_length=200, verbose_name='Complemento do Histórico')),
                ('ced', models.CharField(default='0001', max_length=4, verbose_name='CED')),
                ('ccrd', models.CharField(default='001', max_length=3, verbose_name='CCRD')),
                ('cec', models.CharField(default='0001', max_length=4, verbose_name='CEC')),
                ('ccrc', models.CharField(default='001', max_length=3, verbose_name='CCRC')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientes', verbose_name='Cliente')),
                ('id_conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.creditos', verbose_name='Conta Crédito')),
                ('id_conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.debitos', verbose_name='Conta Débito')),
                ('id_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.historicos', verbose_name='Histórico')),
            ],
        ),
    ]
