# Generated by Django 3.2.7 on 2021-09-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='creditos',
            options={'verbose_name': 'Crédito', 'verbose_name_plural': 'Créditos'},
        ),
        migrations.AlterModelOptions(
            name='debitos',
            options={'verbose_name': 'Débito', 'verbose_name_plural': 'Débitos'},
        ),
        migrations.AlterModelOptions(
            name='historicos',
            options={'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
        migrations.AlterModelOptions(
            name='lancamentos',
            options={'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
    ]
